### ISSUE TITLE
Add summary of selected facets with ‘x’ so that it can be easily removed.

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#102]
As title.

![image](https://user-images.githubusercontent.com/16339290/43589619-00078cde-9667-11e8-99fa-26eb8744d882.png)

https://trello.com/c/nUA2aGm4/21-relocate-reset-filters-button-nearer-the-facet-options-add-summary-of-selected-facets-with-x-so-that-it-can-be-easily-removed

**Comment by crarugal** [comment]
Works well on normal screens, but anything with a width of less than 1015px doesn't work as well as the button to apply changes are out of sight. For example, the simulated iphone6 screen allows me to move the summary of facets up and down, but I'm unable to scroll left or right to press the apply button.

This could be closed, but I would add another issue to fix it for mobile screens.

![image](https://user-images.githubusercontent.com/18530934/45374603-87caf500-b5ea-11e8-9d7d-c8a7fdc827de.png)

Width of 1015px
![image](https://user-images.githubusercontent.com/18530934/45374646-a204d300-b5ea-11e8-848a-5d8f02aa90fb.png)
