### ISSUE TITLE
Add Shadows

### ISSUE THREAD

**Issue by min2ha** [ukwa/ukwa-ui#106]
Add shadows.
Discover shadow parameters from bunnyfoot recommendations design template. 
SearchPage has additional vertical and horizontal pane shadows
All the rest of pages have same shadows dropped from menu panel

**Comment by ldbiz** [comment]
@min2ha sorry, I am not sure how to test this - I need a clear requirements reference to test against. Please will you attach the template, or point to the Trello card with it on.

**Comment by ldbiz** [comment]
@min2ha still awaiting links to and from Trello.

**Comment by min2ha** [comment]
@ldbiz there are no precise shadow parameters provided by bunnyfoot at all. We need closer look at main and search pages to notice it. But it is important for better look.
I was concentrated on the shadows I've noticed:
- Home Page (and the rest pages with blue background stripe, just below the main menu)
![image](https://user-images.githubusercontent.com/15713396/45108419-71c5bc00-b134-11e8-8b13-4c551f826aa7.png)
- Search Page
![image](https://user-images.githubusercontent.com/15713396/45108704-44c5d900-b135-11e8-8f80-54268febe14e.png)

Original pictures/templates are available:
https://trello.com/c/BVdywtEj/23-redesign-access-panel-to-better-communicate-why-only-some-content-is-available-address-subset-and-consistency-issue-only-need-on
https://trello.com/c/6YYwNSB8/6-change-visual-design-too-bland-dated

**Comment by crarugal** [comment]
The shadows are in place but are just slightly darker, there are also a number of small alterations that need to be made if the final version is to mirror bunnyfoot's design. Considering the other more pressing issues, I'm not sure if this has failed or passed as  this small tweak could be added to a list of other minor aesthetic improvements that could be made once the site is fully functional.

https://dev.webarchive.org.uk/en/ukwa/search?text=hello&search_location=full_text&reset_filters=false&content_type=Web+Page

![image](https://user-images.githubusercontent.com/18530934/45300768-2847e900-b507-11e8-9216-713358281c1a.png)

**Comment by crarugal** [comment]
I think this can be closed, but I'll spawn an issue where the shadow could be made lighter to look more like the bunnyfoot version.
