### ISSUE TITLE
Implement Help Dialog

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#109]
![image](https://user-images.githubusercontent.com/16339290/43708832-49ec77b6-9963-11e8-969b-0ab6b633a05d.png)

https://trello.com/c/6YYwNSB8/6-change-visual-design-too-bland-dated

**Comment by min2ha** [comment]
Text needed

**Comment by ldbiz** [comment]
Tip 1 - Use Boolean search terms - AND, NOT, OR etc. e.g. apple NOT fruit.
Tip 2 - Use quote marks when looking for a specific phrase e.g. “London Olympics”.
Tip 3 - Dates refer to when items were collected and not when they were made available on the Internet.

**Comment by ldbiz** [comment]
I don't know how or when this intended to be displayed.

**Comment by ldbiz** [comment]
@min2ha has implemented different text but reckons its irrelevant at the moment, so I'll pass it as it looks ok, we can sort different text later.

**Comment by ldbiz** [comment]
Issue has been committed against after being closed. Reopening, will need retesting.

**Comment by ldbiz** [comment]
Passed.

**Comment by min2ha** [comment]
button bug in IE11
