### ISSUE TITLE
Access panel - wording and tick box.

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#113]
This looks a bit odd and non-standard to me - please clarify exactly what is required before it goes to dev.

![image](https://user-images.githubusercontent.com/16339290/44026632-97ec483c-9eeb-11e8-9af5-561b09b7604c.png)

https://trello.com/c/BVdywtEj/23-redesign-access-panel-to-better-communicate-why-only-some-content-is-available-address-subset-and-consistency-issue-only-need-on

**Comment by nicolabingham** [comment]
Discussed offline with @ldbiz, design has been correctly implemented now.
