### ISSUE TITLE
Welsh archive redirects return 404

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#116]
The welsh result is suffixed _cy which gives 404 when redirecting to ldls. The Scots result doesn't suffix and redirects to the English version.
Example:
https://bl.ldls.org.uk/welcome.html-cy?20170102075541/http://www.bbc.co.uk/programmes/b04tqw6m    >>> 404
https://bl.ldls.org.uk/welcome.html?20170102075541/http://www.bbc.co.uk/programmes/b04tqw6m    >>> ok    (note html does not have suffix)

**Comment by ldbiz** [comment]
Is this an external bug, the url redirect looks correct to me?

**Comment by anjackson** [comment]
Ah this looks like a bug - the Ericom playback system does not properly support direct links to the multilingual interface. i.e. you should go to `https://bl.ldls.org.uk/welcome.html?20170102075541/http://www.bbc.co.uk/programmes/b04tqw6m` no matter what the locale of the UKWA-UI is.

**Comment by ldbiz** [comment]
Bug - should not suffix the "-cy".

**Comment by ldbiz** [comment]
Ah - code was put in place for #27

**Comment by anjackson** [comment]
Okay, so, it depends on the Wayback service you're using:

- If you are sending the user to the Open Access Wayback Service, the `-cy` needs to be added when browsing in Welsh.
- If you are sending the user to a Reading Room Wayback Service, the `-cy` should not be added as those services do not support that feature.

i.e. the implementation of #27 needs to be changed to depend on the context.

**Comment by ldbiz** [comment]
Still redirecting with cy in LDLs - have walked @min2ha through it to clarify.

**Comment by ldbiz** [comment]
Moved to next milestone.

**Comment by ldbiz** [comment]
No change. Welsh pages redirect with cy suffix to Reading Room resources.

**Comment by min2ha** [comment]
@ldbiz could you write precise sequence you've got that 404 error, please?
I couldn't reproduce 404 error.

I didn't get error when I execute in such sequence:
1. go to dev.webarchive.org.uk
2. do search for term "test"
3. select "at libraries"
4. change language to Welsh (Cymraeg)
5. the first link https://dev.webarchive.org.uk/cy/ukwa/wayback/RRO/20170102075541/http://www.bbc.co.uk/programmes/b04tqw6m
redirected me without 404 error to 
https://bl.ldls.org.uk/welcome.html?20170102075541/http://www.bbc.co.uk/programmes/b04tqw6m
6. any link bellow didn't show any 404 errors

**Comment by anjackson** [comment]
Looks like a release sync issue. The test was done at about 10:30 on Friday, but we released the latest version of dev a few hours later (16:00 ish). This issue is now resolved.
