### ISSUE TITLE
Implement Recommended Background on Remaining Pages

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#120]
...en/ukwa/info/terms_conditions
...en/ukwa/info/faq
...en/ukwa/info/notice_takedown
.../en/ukwa/info/cookies
.../en/ukwa/info/privacy

Any others?

Raised in #107 

https://trello.com/c/6YYwNSB8/6-change-visual-design-too-bland-dated

**Comment by ldbiz** [comment]
@nicolabingham comments on Nominate:

I think this would look better if the text is left aligned, to run across the page, not centre aligned as it doesn’t look right with the text in blue boxes left aligned.

**Comment by ldbiz** [comment]
@nicolabingham comments on Contact Us:

the text-entry boxes look a bit elongated perhaps?

The middle paragraph of text “to help answer your questions….” Is also out of alignment with “contact us” and “contact form” which are both left aligned.

**Comment by ldbiz** [comment]
It needs doing for all pages and there are still several outstanding.

We also need to consider the alignment and placement of text, though that possibly needs design input and it may be better to handle that through another issue.

**Comment by min2ha** [comment]
Would it be possible to ask to be more precise about which is/are outstanding? 

When we need to consider the alignment and placement of text?

**Comment by ldbiz** [comment]
Apologies @min2ha, I forgot we changed environment. I will retest.

**Comment by ldbiz** [comment]
No margin on Nominate between the second blue section and the text.

Question for design: should not that second blue section also have the background?

![image](https://user-images.githubusercontent.com/16339290/44517380-6d72bb00-a6bf-11e8-9a6d-2735b37c0fd2.png)

**Comment by ldbiz** [comment]
@nicolabingham design question above: please comment.

**Comment by ldbiz** [comment]
@min2ha please ask @nicolabingham for design input if you need guidance on justification and formatting.

**Comment by min2ha** [comment]
@ldbiz could you explain how what do you call "Justification mismatch on same page"? In adaptive design it is pointless to have constant distance from left or right side, usually it is 10% or 15%. If that mismatch happens on window or screen resize time, it shouldn't be treated as fail.

**Comment by ldbiz** [comment]
Discussed with @min2ha . Just 1. above to be done here, the others to be moved to new issue for design input.

**Comment by ldbiz** [comment]
2. and 3. above now raised as design questions in #135

**Comment by ldbiz** [comment]
@min2ha wrt to 

> could you explain how what do you call "Justification mismatch on same page"? In adaptive design it is pointless to have constant distance from left or right side, usually it is 10% or 15%. If that mismatch happens on window or screen resize time, it shouldn't be treated as fail.

There were no resize operations. Just looking at different menu pages (as the examples above), the difference in justification is clear.

**Comment by min2ha** [comment]
Honestly I do not understand what is the point to pay too much attention on details, which are not related to the task? Task states **Recommended Background on Remaining Pages**. Text margins and justification should be move to next issue. 
(BTW I've aligned text to the left side in advance, because old centred text version looks even more ugly).

**Comment by ldbiz** [comment]
@min2ha if a consequence of developing an issue is that new problems are introduced, that issue has not been properly implemented. Then a call has to be made as to how they are handled. Please see previous comment - 1. needs fixing against this issue.

When you have done that, please mark it ready for testing and I will test it. 

If you think you won't have time, we can make a decision on dropping this issue from the milestone, or raising another issue.

**Comment by ldbiz** [comment]
This issue is being moved to the next milestone.

**Comment by crarugal** [comment]
I'm looking at the dev version. Not sure if this is a fail as the background is in place, but perhaps the main heading should be without additional text. The  text "To help answer any questions you may have about the UK Web Arch........." looks like it should be separated from the main heading and instead be placed underneath.

https://dev.webarchive.org.uk/en/ukwa/contact

![image](https://user-images.githubusercontent.com/18530934/45297025-e49bb200-b4fb-11e8-9403-05bc8776ebd8.png)

**Comment by crarugal** [comment]
Should the 404 or any other error page have a background similar to other headings? Also the "Go back" function looks a bit out of place, it could be aligned or maybe placed as a button beneath the 404 error heading.

https://dev.webarchive.org.uk/en/n/ukwa/info/privacy


![image](https://user-images.githubusercontent.com/18530934/45297507-853ea180-b4fd-11e8-900f-51e7518a2e87.png)

**Comment by crarugal** [comment]
I think this could be closed, but I'll create two new possible issues: 
1) rearrange Contact Us page header text
2) add background to error pages, e.g. 404 page
