### ISSUE TITLE
Reset Filter - add 'x' in the corner of field of chosen filter criteria

### ISSUE THREAD

**Issue by min2ha** [ukwa/ukwa-ui#133]
Add 'x' in the corner of field in order Easy to remove filter criteria

![image](https://user-images.githubusercontent.com/15713396/44463032-5b850f80-a60e-11e8-95c4-5525fae5c19a.png)

**Comment by ldbiz** [comment]
@min2ha please will you add references to and from the Trello card that guides this issue.

**Comment by ldbiz** [comment]
Still awaiting design references as previous comment.

**Comment by min2ha** [comment]
@ldbiz design reference could be found at:
https://trello.com/c/nUA2aGm4/21-relocate-reset-filters-button-nearer-the-facet-options-add-summary-of-selected-facets-with-x-so-that-it-can-be-easily-removed

original design is shown above.

**Comment by crarugal** [comment]
The added reset to faceting functionality works, so I'll close this. But I've noticed another issue with the search box, it's also present in Alpha.

The search box is squeezed in mobile; I'll create a new issue if it hasn't already been flagged.

![image](https://user-images.githubusercontent.com/18530934/45372155-2c960400-b5e4-11e8-8c90-4e9aab253a9c.png)
