### ISSUE TITLE
Facet search - zero result

### ISSUE THREAD

**Issue by min2ha** [ukwa/ukwa-ui#140]
Facet search - using check boxes getting zero result.
For example it shouldn't be listed **.co.uk** domains if suffix **com** was selected before and vice versa.

![image](https://user-images.githubusercontent.com/15713396/45360289-fc8c3800-b5c6-11e8-90e0-9495a545397d.png)

**Comment by crarugal** [comment]
I chose a different domain with .com and the the suffix kept at .com, results were returned

![image](https://user-images.githubusercontent.com/18530934/45545131-49fbe580-b811-11e8-98b9-3a9d2cf674b9.png)

**Comment by crarugal** [comment]
Could it be that results are only returned if domain facet has the same suffix as the chosen suffix facet? Eg. Domain = "guardian.com" and Suffix = "com"

**Comment by crarugal** [comment]
I tried another search where the Domain suffix had "net" and Suffix facet was "net"; results were returned.

![image](https://user-images.githubusercontent.com/18530934/45545351-e8884680-b811-11e8-88ac-b2ad27c5099a.png)

**Comment by min2ha** [comment]
@crarugal, IMHO, filter must reflect exact selection and correct other facet filters to avoid zero returns. Zero return exception could be search keyword only. Ebay is good example, tho.

**Comment by crarugal** [comment]
@min2ha Yeah I agree, I think that both the Domain suffix facet and Suffix facet should be mutually exclusive; in that choosing bbc.co.uk should then remove the option to choose other suffixes other than .co.uk. Perhaps options should be greyed out or removed entirely depending on your facet choices.

**Comment by crarugal** [comment]
Seems to be working well, choosing a domain will limit your choices of suffixes, If the domain and the suffix are both selected, removing the domain choice will still retain the suffix choice and present all available corresponding domains.
 E.g. if co.uk. suffix is chosen, only domain with .co.uk will be presented.
![image](https://user-images.githubusercontent.com/18530934/45759691-583a6f00-bc20-11e8-9d11-456bab669b41.png)

**Comment by crarugal** [comment]
Solution still works with different suffix

![image](https://user-images.githubusercontent.com/18530934/45760407-e400cb00-bc21-11e8-9794-45d0167e1aa0.png)

**Comment by min2ha** [comment]
@crarugal in Facet Filter Dialog selection reflection on other Tabs is not updating dynamically at the moment. Dialog version is working a bit different to compare with basic, non-dialog version. I thought of it, it could be treated as bug.

**Comment by crarugal** [comment]
I'll move the other issue to a new issue as the original issue was fixed.
