### ISSUE TITLE
Error page header backrgound

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-ui#142]
Do the error pages such as 404 require the same header background as used by the static pages?

Spawned from: Implement Recommended Background on Remaining Pages #120, 1.1.3 Alpha Iteration 3
#120

https://dev.webarchive.org.uk/en/n/ukwa/info/privacy

![image](https://user-images.githubusercontent.com/18530934/45364664-a02f1580-b5d2-11e8-88a0-f8bb201905a5.png)

e.g.
![image](https://user-images.githubusercontent.com/18530934/45364836-0b78e780-b5d3-11e8-8f67-391420e88c2e.png)

**Comment by min2ha** [comment]
Fix includes re-designed headers for errors 404 and 500

**Comment by crarugal** [comment]
Thanks Mindy

![image](https://user-images.githubusercontent.com/18530934/45486765-2fb00200-b754-11e8-9892-a9ef36ee2c7b.png)
