### ISSUE TITLE
consider changing the text provided when hovering over the question mark.

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-ui#143]
The the text is generic and perhaps unhelpful to the average user, does this need to be changed?

Spawned from issue Facet text improvements #99, 1.1.3 Alpha Iteration 3
https://github.com/ukwa/ukwa-ui/issues/99

![image](https://user-images.githubusercontent.com/18530934/45368852-7aa70980-b5dc-11e8-8865-95ee729a5a09.png)

**Comment by nicolabingham** [comment]
Suggest replacing "Domain facet help tooltip" with "Narrow your search results to a particular domain, or website."

**Comment by min2ha** [comment]
@nicolabingham thanks for suggestion! 
This phrase will need translations too.

**Comment by crarugal** [comment]
Yeah the translations still need to be done, but I think that's a large job that needs more clarification and is perhaps part of issue #117 .

![image](https://user-images.githubusercontent.com/18530934/45495102-7b6da600-b76a-11e8-929f-c42e150b65be.png)


![image](https://user-images.githubusercontent.com/18530934/45495106-7e689680-b76a-11e8-8267-6bea68fdc1ab.png)
