### ISSUE TITLE
Search box squeezed in mobile

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-ui#145]
When using a smaller screen, specifically anything below 448px wide, the search box is squeezed smaller by the search button; in its smaller state the search text is hidden and the ability to type is removed.

![image](https://user-images.githubusercontent.com/18530934/45372999-3caee300-b5e6-11e8-8713-f8001e4751bf.png)

**Comment by jasonwebber-bl** [comment]
Seems to work ok now.
