### ISSUE TITLE
Remove filter - Accessing Content - Logic issue

### ISSUE THREAD

**Issue by min2ha** [ukwa/ukwa-ui#148]
Accessing Content is more general filter, and it seems that there is no point to remove it.
'x' is useless.

**Comment by crarugal** [comment]
![image](https://user-images.githubusercontent.com/18530934/45543997-fd62db00-b80d-11e8-824f-ba820a02f5b1.png)

**Comment by crarugal** [comment]
Seems to be working well

![image](https://user-images.githubusercontent.com/18530934/45811464-14e60c00-bcc5-11e8-90e7-84bbf053c8bd.png)


![image](https://user-images.githubusercontent.com/18530934/45811469-16afcf80-bcc5-11e8-95ea-3293d43c9cdb.png)
