### ISSUE TITLE
Place holder images; keep or change?

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-ui#161]
Currently there are over 30 placeholder images being used for the special collections; I think we do have many images that we can use that were found by our summer intern. If we don't have those images, is there a better alternative placeholder image?

![image](https://user-images.githubusercontent.com/18530934/46158841-a4b42900-c276-11e8-84da-621ea27cae35.png)

**Comment by nicolabingham** [comment]
The current placeholder image is the screen/code image but you're right we should source a better one... I'll have a look.

**Comment by jasonwebber-bl** [comment]
Do we still want to source a better placeholder image?

**Comment by nicolabingham** [comment]
It's up to you @jasonwebber-bl
