### ISSUE TITLE
Clearing filters are formatting incorrectly for titles with commas

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-ui#163]
If a facet clearing option has a long title with commas, it seems that the title will be broken up into boxes depending on how many commas are present. This seems to only effect Topics and Themes titles as no other facet have titles with commas.

For example:

Topics and Themes: "Muslims, Trust and Cultural Dialogue", has one comma and produces this result:
![image](https://user-images.githubusercontent.com/18530934/46205995-8e5fa900-c31a-11e8-8bab-8b318b0c55bd.png)

Topics and Themes: First World War Centenary, 2014-18, ", also has one comma and produces this result:
![image](https://user-images.githubusercontent.com/18530934/46206018-9f101f00-c31a-11e8-80cd-f899f0c6796f.png)

Topics and Themes: "Health and Social Care Act 2012 - NHS Reforms" is not broken up as there are no commas
![image](https://user-images.githubusercontent.com/18530934/46206360-b26fba00-c31b-11e8-8ab1-509588fddeeb.png)

**Comment by jasonwebber-bl** [comment]
Tested. Resolved. Ready to go live.
