### ISSUE TITLE
Change images on 'about us' page.

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#167]
The images of the book shelves and the BL should be changed to something neutral.

Server stack?
Reading room terminal (being used)?

**Comment by crarugal** [comment]
![image](https://user-images.githubusercontent.com/18530934/46339602-24e9de00-c62b-11e8-8924-fb800f44a808.png)

**Comment by nicolabingham** [comment]
Hi Jason, when you say neutral, do you mean non-LDL specific?

**Comment by jasonwebber-bl** [comment]
Yes, but if that's impossible probably not a picture of the BL specifically.

**Comment by nicolabingham** [comment]
OK, cool.

**Comment by min2ha** [comment]
Sorry, just wondering who is going to suggest the neutral pictures?

Anyway, how about those?

**Reading room terminal**
![5a27b4107cd25846093721](https://user-images.githubusercontent.com/15713396/46603169-34b16880-caea-11e8-8075-a91e9f9f84da.png)
![digital-lib-photo-1](https://user-images.githubusercontent.com/15713396/46603174-3549ff00-caea-11e8-9a82-e93da33dfe15.jpg)

**Server stack**
![482872096-2048x2048](https://user-images.githubusercontent.com/15713396/46603170-34b16880-caea-11e8-9f73-b2a21efa2464.jpg)
![802301510-2048x2048](https://user-images.githubusercontent.com/15713396/46603172-34b16880-caea-11e8-8777-22e45ffbb388.jpg)
![802320836-2048x2048](https://user-images.githubusercontent.com/15713396/46603173-3549ff00-caea-11e8-96f5-d7fe4ff69b20.jpg)

**Comment by nicolabingham** [comment]
I like the second one, with the people in the middle of the wave. Is it a right's cleared image?

**Comment by jasonwebber-bl** [comment]
Is it not a breach of trade descriptions? I was thinking of a picture of the actual machines is alright.

**Comment by jasonwebber-bl** [comment]
This one instead of the book shelves:

![_mg_0504](https://user-images.githubusercontent.com/33252622/47007971-466dbe00-d131-11e8-9807-04942f2a2816.JPG)

**Comment by jasonwebber-bl** [comment]
Instead of the BL building

![british-library-reading-room-2](https://user-images.githubusercontent.com/33252622/47008070-7b7a1080-d131-11e8-9d34-e511f23a3a8a.jpg)

**Comment by jasonwebber-bl** [comment]
Images are fine.
