### ISSUE TITLE
Filter is buggy when switching languages

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#17]
Home Page >
Enter a search term (no filter) > 
n results returned >
Change language (e.g. change from English to Welsh) >

**Issue 1**: 0 results returned for "" (keyword has been reset) >

Enter a keyword and search >

**Issue 2**: 0 results returned for ""  (but a keyword has been supplied) >

Reset filters >
Enter search term >
n results returned

**Issue 3**: Why do filters need to be reset? We haven't set them!

**Comment by min2ha** [comment]
https://github.com/ukwa/ukwa-ui/issues/116
