### ISSUE TITLE
Inconsistent naming of language options

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#18]
The language labels (English/Welsh/Scottish) appear to be displayed inconsistently in the different languages.

E.g. I would expect the label to be in the language of that to be selected.

So on an English or Scottish page, "Welsh" would be displayed as "Cymraeg", not "Welsh", say.

However on the English and Scottish pages this is so, whereas on the Welsh page:

"English" is displayed as "Saesneg" - the Welsh for "English". Should be "English".

Scottish"is displayed as "Gaeleg yr Alban" - the Welsh for "Scottish Gaelic". Should be whatever the Scottish Gaelic of "Scottish Gaelic" is. Presumably "Gàidhlig" as that's on the English page.

**Comment by ldbiz** [comment]
Design decision: The issue is as described - the labels should be in the language of that to be selected.

**Comment by min2ha** [comment]
Prevoiusly we used "About", re-design requires to use "About Us". Could somebody provide propper translation?

**Comment by crarugal** [comment]
The language options issue looks fine, I'll create another issue with

Looking at the Welsh and Scottish pages, there seems to be a spattering of English; which seems unlikely to be resolved by the end of this milestone. If translations are needed, perhaps it should be done when all the English text is locked down.

Translations of text has been referenced in issues:

Text translations still not provided #117
