### ISSUE TITLE
Java Mail not working

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#190]
The UI can't send emails, because it's not pickup if the configuration. Seems to be an instance of this: https://stackoverflow.com/questions/46931283/spring-mail-starter-ignoring-spring-mail-config

This explicit declaration was added in https://github.com/ukwa/ukwa-ui/commit/b3c4c9883092e6acc86ddeebe755701265975595

/cc @min2ha in case there's a specific reason we can't just remove this Bean definition and let it autowire?

**Comment by anjackson** [comment]
@min2ha let me know if this breaks things for some reason.

**Comment by min2ha** [comment]
@anjackson I've tested email with @crarugal few weeks ago and it was working fine. Further investigation will be needed.

**Comment by anjackson** [comment]
Okay I think we're fine now -- having restored the bean I should not have taken our, dev seems to be running fine and sending an email did not fail. If @crarugal can verify the email was received we can call this done.

**Comment by anjackson** [comment]
Okay I think we're fine now -- having restored the bean I should not have taken our, dev seems to be running fine and sending an email did not fail. If @crarugal can verify the email was received we can call this done.
