### ISSUE TITLE
Collection Summaries and other Information appear to be Hard coded

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#193]
Is this correct, and is there a reason for why they are not derived from data? 

https://github.com/ukwa/ukwa-ui/blob/master/src/main/resources/collectionSearchStub.json
https://github.com/ukwa/ukwa-ui/blob/master/src/main/resources/contentSearchStub.json

Noted when looking for the summary data to correct a spelling mistake (#194 )

**Comment by min2ha** [comment]
Spelling mistake in a Collection Summary #194
