### ISSUE TITLE
Technical Info Page missing

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#202]
Formerly https://www.webarchive.org.uk/ukwa/info/technical

Example reference:

https://library.columbia.edu/bts/web_resources_collection/guidelines_for_preservable_websites.html

**Comment by ldbiz** [comment]
Previous page example:

https://www.webarchive.org.uk/wayback/en/archive/20140806154211/http://www.webarchive.org.uk/ukwa/info/technical/

**Comment by HelenaByrne** [comment]
Additionally the 404 error message does not translate into Welsh, but everything else the page does. https://www.webarchive.org.uk/cy/ukwa/info/technical?

**Comment by ldbiz** [comment]
Technical info page not there, don't know why this has been closed.

@HelenaByrne I think your observation needs a separate issue for error translation. I'll create one if I can't find one.

**Comment by HelenaByrne** [comment]
Thanks @ldbiz

**Comment by anjackson** [comment]
Okay, so what's happening is Mindy is closing tickets when the work is done, but this does not mean the code is deployed yet. 

@min2ha the change should be visible on dev, right?

**Comment by ldbiz** [comment]
yes, you are correct, its on dev, thanks.

Needs formatting, there's no paragraphs and certain diacritics seem to be getting in the way.

Also, there is no link I can see from the main menu, but I guess that's how it was and would be a design decision and separate issue.

I do think the formatting needs revisiting tho.

**Comment by ldbiz** [comment]
Also the window title is "Privacy"

**Comment by min2ha** [comment]
@anjackson I'm not sure what was the problem. **dev server** purpose is to test modifications, isn't it?
From my point of view initial technical page implementation is done and it is available on
https://dev.webarchive.org.uk/en/ukwa/technical

But IMHO it needs to be checked against the law, because it is old version.

**Comment by ldbiz** [comment]
@min2ha please see my comments on formatting and window title.

**Comment by anjackson** [comment]
Hi @min2ha it's just caught us out because previously we were tagging completed issues for tested and closing them after testing, I think?

We could set up a dedicated GitHub Project Kanban board if that would help?

**Comment by anjackson** [comment]
Oh and hah yes it's rather out of date! Ahem. I'll come up with some fresh text...

**Comment by min2ha** [comment]
@ldbiz @anjackson it seems to be fair enough for me to put label **testing: ready to test** in order if the issue was not raised my myself. This pattern could be used for all new issues in the future.

If GitHub Project Kanban board may help to avoid labelling, or any duplication I don't mind. Anyway worth to try it and we'll see if development will become more productive.

**Comment by anjackson** [comment]
I've put the original text reformatted as Markdown [here](https://github.com/ukwa/ukwa-site/blob/master/content/info/technical/index.md) and I'll edit it tomorrow. It'll probably need review from @nicolabingham and @jasonwebber-bl too.

**Comment by min2ha** [comment]
@jasonwebber-bl technical page needs translation after check against the law & update.

**Comment by anjackson** [comment]
Okay, updated a draft here: https://github.com/ukwa/ukwa-site/blob/master/content/info/technical/index.md

How's that looking @nicolabingham and @jasonwebber-bl

**Comment by nicolabingham** [comment]
sounds good @anjackson thanks.

**Comment by anjackson** [comment]
Present on beta.
