### ISSUE TITLE
Errors need translations.

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#215]
e.g. 404 - Error is in English on Welsh pages. Raised in #202

**Comment by ldbiz** [comment]
@jasonwebber-bl, @nicolabingham  please can we have translations for the following, then assign to @min2ha 

cheers

> error.404.title = UKWA 404 error - Page not found
> error.404.back.button = Go back
> error.404.heading = 404 error - Page cannot be found
> error.404.text = Please check the URL
> error.404.note = Please <a href="contact">contact</a> us with the details if you are unable to find what you are looking for.
> 
> error.500.title = UKWA 500 error - Server error
> error.500.back.button = Go back
> error.500.heading = 500 error - Server error
> error.500.text = Please try again
> error.500.note = Please <a href="contact">contact</a> us with the details if you get this error again. 
>

**Comment by jasonwebber-bl** [comment]
This is part of the translations ticket #258. I think we can close this one?
