### ISSUE TITLE
Top Menu Minimisation for Mobile devices 

### ISSUE THREAD

**Issue by min2ha** [ukwa/ukwa-ui#216]
Top Menu Minimisation for lower resolution screens, aka Mobile devices.
(Lower resolution screens, do not have enough space for full list of menu. It is more convenient to use when specific content is minimised into single button or link)

**Comment by anjackson** [comment]
As part of the accessibility review, I have switched to a standard Bootstrap 4 navbar with the standard menu collapse behaviour. I think that resolves this issue too?
