### ISSUE TITLE
RSS feed not working

### ISSUE THREAD

**Issue by min2ha** [ukwa/ukwa-ui#222]
RSS feed - Footer Link to https://www.webarchive.org.uk/rss/recent.xml
Need to (auto) generated XML 

(We could create separate Rss Feed Controller)

**Comment by anjackson** [comment]
As part of the accessibility review, I have simply removed this link. I suggest we defer RSS feed implementation to the deployment of the newer statically-generated site: https://github.com/ukwa/ukwa-site
