### ISSUE TITLE
Search results for URLs with query parameters not being passed through

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#226]
e.g. the search results from "test" currently include this link:

https://www.webarchive.org.uk/en/ukwa/wayback/OA/20160218233720/http://www.nystagmusnet.org/phpBB3/viewtopic.php?f=5&t=35686&view=print

which gets redirected to 

https://www.webarchive.org.uk/wayback/en/archive/20160218233720/http://www.nystagmusnet.org/phpBB3/viewtopic.php

but it should get redirected to

https://www.webarchive.org.uk/wayback/en/archive/20160218233720/http://www.nystagmusnet.org/phpBB3/viewtopic.php?f=5&t=35686&view=print

i.e. with the query parameters included.

**Comment by anjackson** [comment]
Here is an example of the problem

```
$ curl -I "https://www.webarchive.org.uk/en/ukwa/wayback/OA/20160218233720/http://www.nystagmusnet.org/phpBB3/viewtopic.php?f=5&t=35686&view=print"
HTTP/1.1 302 
Server: nginx/1.14.0
Date: Mon, 11 Mar 2019 11:50:07 GMT
Connection: keep-alive
Location: https://www.webarchive.org.uk/wayback/en/archive/20160218233720/http://www.nystagmusnet.org/phpBB3/viewtopic.php
Content-Language: en
```

**Comment by min2ha** [comment]
AntPathMatcher removed, because it didn't work with such symbol sequence in that type of URLs:
http://www.welshconservatives.com/news/6-years-no-equitable-access-down%E2%80%99s-syndrome-test
