### ISSUE TITLE
All links broken in search results

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#231]
All the links coming back in the search results are going straight to the live web rather than the web archive!  They should go to the relevant Wayback service.

I think this change was mistake https://github.com/ukwa/ukwa-ui/commit/210e04b23e00916e17248b738a2e315c106634ae

**Comment by anjackson** [comment]
n.b. this arose while attempting to resolve #226

**Comment by min2ha** [comment]
It should be closed
