### ISSUE TITLE
Update TCD logo for UI

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/ukwa-ui#233]
Trinity College Dublin have requested that we change thier logo on the UI as the current one is out of date. The new logo is copied below. 
![TCD_logo](https://user-images.githubusercontent.com/11210500/54344635-36eb9600-4639-11e9-8daa-5e90a174b44e.png)

**Comment by jasonwebber-bl** [comment]
Hi Mindy

I see the footer logo has been updated. I realise that we also need to amend this one that is on the 'about us page'. Are you ok to incorporate the new TCD image into it?

![UKWA-about-logos](https://user-images.githubusercontent.com/33252622/100358573-45850700-2fee-11eb-8767-a6d97d87d5e7.png)

**Comment by jasonwebber-bl** [comment]
new combined logo
![UKWA-about-logos](https://user-images.githubusercontent.com/33252622/100455824-46ce3680-30b7-11eb-9e3a-cb64c5685841.png)
