### ISSUE TITLE
Footer links changed accidentally

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#243]
It looks like this change https://github.com/ukwa/ukwa-ui/commit/93607f1db745a48fd5809b03f997d15a4ccac35c killed some footer links.

In particular, the links to `terms_conditions` is broken, but the other should be checked.

The BL appears to have changed it's privacy policy too, c.f. #128

**Comment by GilHoggarth** [comment]
This hasn't been fixed yet; the link in UKWA footer still returns the homepage.

**Comment by GilHoggarth** [comment]
Or perhaps the fix hasn't been rolled out. Either way, still broken on live.

**Comment by crarugal** [comment]
![image](https://user-images.githubusercontent.com/18530934/96117756-7992e580-0ee2-11eb-9044-9a411272405c.png)
 all links appear to be working now
