### ISSUE TITLE
Add Scottish Gaelic Accessibility Statement to the website 

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/ukwa-ui#247]
Could this be linked to from the English version of the statement, as we don't have a Scottish Galeic version of the website at the moment?
[Accessibility Statement UKWA_JF_NB_edit gaidhlig.docx](https://github.com/ukwa/ukwa-ui/files/3641829/Accessibility.Statement.UKWA_JF_NB_edit.gaidhlig.docx)

**Comment by anjackson** [comment]
okay, translation currently hacked into the English page: https://beta.webarchive.org.uk/en/ukwa/info/accessibility_statement

Okay to roll this out?

Longer term plan should be to finish the translations!

**Comment by nicolabingham** [comment]
Yes please @anjackson and yes, we should pick up the translations.
