### ISSUE TITLE
Add Welsh version of accessibility statement to the website 

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/ukwa-ui#248]
The Welsh translation of the accessibility statement is to be added to the website please. 
[CY Accessibility Statement UKWA_JF_NB_edit (813)_cyfieithiad.docx](https://github.com/ukwa/ukwa-ui/files/3651628/CY.Accessibility.Statement.UKWA_JF_NB_edit.813._cyfieithiad.docx)

**Comment by anjackson** [comment]
Okay, Welsh version now live on BETA: https://beta.webarchive.org.uk/cy/ukwa/info/accessibility_statement
