### ISSUE TITLE
Collection image: Royal Colleges of Health and Medicine

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/ukwa-ui#250]
Could this image be added to the Royal Colleges of Health and Medicine Collection (id 2738) on the Topics and Themes page please? https://www.webarchive.org.uk/en/ukwa/collection
![RoyalCollegesCollection](https://user-images.githubusercontent.com/11210500/67769218-f156ce80-fa4b-11e9-9f95-58f78c78aa5b.jpg)

**Comment by jasonwebber-bl** [comment]
Tested. Looks great. Put to live.
