### ISSUE TITLE
Search box layout all weird under IE11

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#251]
Despite the (c) 2013 nature of IE11, we're still using it. And the layout looks weird.  Maybe just missing some classes.

![image](https://user-images.githubusercontent.com/87843/69430269-1974dd00-0d2d-11ea-86f3-ac07b69bf170.png)

**Comment by min2ha** [comment]
Generated view is related to specific resolution. According to responsive web design (RWD), some tuning of screen width and height should be enough. Unless it's some IE specific exception.

**Comment by anjackson** [comment]
It’s an IE11 specific exception. Like I say I likely missed Bootstrap class to do with the layout.

**Comment by min2ha** [comment]
similar side effect is on the rest of titles of other pages. Hope to fix it in same commit.
