### ISSUE TITLE
Check URL lookup is working as expected

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#252]
Originally, the UKWA-UI was designed to spot when a URL was passed as the search term, and check Wayback/CDX to see whether we had it. If so, a result was inserted at the top of the results page, taking the user straight to Wayback to see the exact match.

We need to check if this is still in place and working. Test searches:

 - [www.oneandother.co.uk](https://www.webarchive.org.uk/en/ukwa/search?view_filter=va&content_type=Web+Page&from_date=&to_date=&modal_filter_domains_vals=&modal_filter_suffix_vals=&modal_filter_documenttypes_vals=&modal_filter_collections_vals=&filter_source=1&filter_array_x=&filter_array_x_item=&search_location=full_text&text=www.oneandother.co.uk&view_sort=relevant&view_count=50)
- [www.webarchive.org.uk](https://www.webarchive.org.uk/en/ukwa/search?view_filter=va&content_type=Web+Page&from_date=&to_date=&modal_filter_domains_vals=&modal_filter_suffix_vals=&modal_filter_documenttypes_vals=&modal_filter_collections_vals=&filter_source=1&filter_array_x=&filter_array_x_item=&search_location=full_text&text=www.webarchive.org.uk&view_sort=relevant&view_count=50)

This could equally be implemented in the Solr search is we add a suitable option-but-boosting search field.

**Comment by anjackson** [comment]
Note that the `all` alias is missing the `selective-` index at the moment, so that's the main reason the results are so poor (ping @GilHoggarth). But the exact-match behaviour needs checking anyway.

**Comment by anjackson** [comment]
n.b. I think this is the same basic issues as #253

**Comment by min2ha** [comment]
Sorry, could somebody comment the results?

<img width="1421" alt="Screenshot 2020-10-14 at 15 51 59" src="https://user-images.githubusercontent.com/15713396/95991501-83aada80-0e35-11eb-8c5d-b821152e6f81.png">
<img width="1426" alt="Screenshot 2020-10-14 at 15 52 49" src="https://user-images.githubusercontent.com/15713396/95991513-87d6f800-0e35-11eb-8d6a-7ff996fbc4d5.png">

**Comment by anjackson** [comment]
This should work but does not: https://www.webarchive.org.uk/en/ukwa/search?text=https%3A%2F%2Fwww.abortionresistance.org.uk%2F&search_location=full_text&reset_filters=false&content_type=Web+Page

So this is certainly broken.

**Comment by anjackson** [comment]
Yep, it just does a URL search on Solr, not against CDX, and indeed there's nowhere where it even knows where the CDX is as far as I can tell.

https://github.com/ukwa/ukwa-ui/blob/465e94c7e4e1f12f2467c5f5cab4c9f98a579df6/src/main/java/com/marsspiders/ukwa/controllers/SearchController.java#L161-L173

**Comment by anjackson** [comment]
Superceded by URL search form.
