### ISSUE TITLE
HTTP/HTTPS - URL search issue

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#253]
If a user copies and pastes a url from a live site it will usually be HTTPS these days e.g. https://www.bbc.co.uk/. Historical archived versions may only be HTTP which sometimes means that the search gives no result when in fact there is a valid website in the archive. Conceivably this might also happen the other way around too.

Can url searches be tailored to take account of this? Searching by these different methods also yields different results (maybe that is a different ticket). 

![image](https://user-images.githubusercontent.com/33252622/70225805-a6fdf700-1747-11ea-92df-2ccef1e5d725.png)
![image](https://user-images.githubusercontent.com/33252622/70226036-065c0700-1748-11ea-9f3c-5aaa5011bacb.png)

**Comment by anjackson** [comment]
We generally search for http and https when looking up a URL, so that this is apparently not happening for URL searches seems like a bug to me.

**Comment by jasonwebber-bl** [comment]
Tested. Works as expected. Ready to go live.
