### ISSUE TITLE
Topics and Themes categorisation

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#257]
Implement categorisation of the Topics and Themes and display these on the T and T page.

Phase 1 - Identify examples and in liaison with Mark Whiting & James Rennie to develop and adapt Wire Frames for presentation of High Level Collection areas. **Responsible & Accountable: JW; Consulted: NB, AJ, LDLs**

Phase 2 - Implement High Level Collection areas using design agreed in Phase 1. Include translations to Welsh and Scottish Gaelic. **Responsible: MV; Accountable: JW; Consulted: NB, AJ, LDLs**

**Comment by jasonwebber-bl** [comment]
List of category names:

- Arts and Culture
- History
- Politics and Government
- Places
- Science Technology and Medicine
- Society and Community
- Sport and Recreation

**New Topics and Themes landing page:**
![ukwa-TpThe-06](https://user-images.githubusercontent.com/33252622/125622393-aedcdede-d566-4b8b-9802-470d40fbaa06.jpg)

- Two rows of four images (Note: 8th image can be a link to ‘all collections')
- Include a link to ‘A-Z of all collections’


**Category page**
<img width="1134" alt="ukwa-TpThe-04" src="https://user-images.githubusercontent.com/33252622/125622610-54daad24-7cb7-44eb-ba11-b8aea281596b.png">

- Add left hand column to Topics and theme with categories in alphabetical order
- Categories should include number of collections they contain (in brackets)
- Ability of user to toggle images on and off (like current collections page)


**A-Z list**
<img width="1134" alt="ukwa-TpThe-03" src="https://user-images.githubusercontent.com/33252622/125622768-dfa3565e-a30c-4013-a641-45ebf98d63e0.png">

- Explore if ‘expanding list’ is possible to include sub collections

**Comment by jasonwebber-bl** [comment]
Suggested category images: https://docs.google.com/document/d/1ejI91AZwGoqS2Y-B-zROjg6wytdw_fU1AYa-zEXRQhk/edit?usp=sharing

**Comment by jasonwebber-bl** [comment]
Feedback to v1, v2, v3 and v4;

Version 2 is the standout example and the one we should develop further. 
**Action: 
- Reduce to 7 tiles.
- Add link at top 'List all topics and themes'
- Add description (take from T&T page)**

Version 4 is a great start to the T&T 'results' page
**Action:
- Give the page UKWA branding
- Include full list of all 7 categories (inc no. of T&T in each) - Question: is the number the real one? Is it auto-generated?
- Note: There are only collection images for top level collections. No plans for images for sub-collections.
- The example of the nesting of the main-collection/sub-collection and sub-sub-collection is great, can we get a working version?
**

**Comment by jasonwebber-bl** [comment]
Feedback from latest version - 6 dec 2021

1. Add search box to categories home page - search should be against ALL categories and take you to the results page.
2. Add link 'See all topics and themes' to categories home page.
3. On category homepage - remove text: 'current status available' from category boxes
4. On category page - make single column (remove left hand column), move no. of collections to top of page (under a-z). Remove others figures and box
5. Make list of topics and themes in alphabetical order
6. Optional for this release - category page - On each topic in list for the open v library only numbers, add text: 'Viewable online' and 'At libraries'. Add an 'i' so we can explain this.

**Comment by iancooke-webarchive** [comment]
Following our Team call on 8 Dec, I'd like to suggest the following as essential and desirable requirements. Suggest we use essential for first iteration and then come up with a priority list for the desirable:
### Essential
High-level categories start page, that lists the 7 categories and provides navigation to each category page
Include images for each category on start page
7 category pages for: Science, Technology and Medicine; Sport & Recreation; History; Politics & Government; Arts & Culture; Places; Society & Communities
Each category page is mapped to the Topics and Themes collections that have been allocated to that category in ACT
The Topics and Themes collections are displayed in alphabetical order on each category page
Each Topic and Theme collection displays a: title; the first 450 characters from the description; and a link to the collection in the User Interface
Each category page allows navigation to the other category pages and start page. This should be at the top of the page.   
Create a ‘high contrast’ version of start page and each category page for accessibility
Create Welsh language version of pages (individual collection titles and descriptions will not be in Welsh unless this already exists)
Create Scottish Gaelic version of pages (individual collection titles and descriptions will not be in Scottish Gaelic unless this already exists)
Check all new content for accessibility compliance

### Desirable
Each Topic and Theme collection has a thumbnail image.
Information is displayed for each collection, to show how many targets are accessible remotely, and how many require the user to be on library premises
‘Filter collections’ feature that allows free text search of collection title and description 
Create results display page for Filter Collections search. This should be similar in layout to category page.
Create ‘no search results’ page with suitable onward journey
 Display of additional information about each category with category image (eg number of collections)

**Comment by jasonwebber-bl** [comment]
Remaining items (9 Feb 2022):
- Exchange 'art and culture' image with the paint picture below.
![pexels-dan-cristian-pădureț-1193743](https://user-images.githubusercontent.com/33252622/153164007-674f5d26-f389-477f-8bfa-fea0972a224a.jpg)
- Exchange 'places' image with the signpost one below
![javier-allegue-barros-C7B-ExXpOIE-unsplash](https://user-images.githubusercontent.com/33252622/153164306-1ae38834-c802-409d-ba3e-762696d37c53.jpg)
- The gap (white space) between the collection image and the description text should be bigger (by 5 pixels??). It is difficult to give an exact number but currently the text is too hard up against the image.
<img width="847" alt="image" src="https://user-images.githubusercontent.com/33252622/153164841-e36b4c89-efe6-46fb-803b-687918a3b964.png">
- The 'hand' symbol (to denote a link) does not come on the cursor when hovering on the category images. It currently stays as an arrow.
- The number of collections when first coming to the page says 243 (which is incorrect). If you pick another category and go back to 'all collections' it gives the correct number of 111.
- List the new text that requires translation - JW to send to NLW and NLS.

**Comment by jasonwebber-bl** [comment]
Text for translation (Mindy, please confirm):

Arts and Culture
History
Politics and Government
Places
Science Technology and Medicine
Society and Community
Sport and Recreation
Filter within all categories (xxx collections available)
No results
Results found
Show more
Show less

**Comment by min2ha** [comment]
> Text for translation (Mindy, please confirm):
> 
> Arts and Culture History Politics and Government Places Science Technology and Medicine Society and Community Sport and Recreation Filter within all categories (xxx collections available) No results Results found Show more Show less

Probably it would be good to follow existing order and have description of an input field, for the text when filtering the T&T. 
For example for the general search we have such aria-label/tip:  
`Enter a specific website URL (e.g. www.bl.uk) or any word or phrase...`
it could be:
`Enter a specific word or phrase to filter category`

**Comment by jasonwebber-bl** [comment]
A summary of feedback: https://docs.google.com/document/d/1U50GgSLbpYMXe3gjW8vi4jSrPSOnSM_tGTMUWH_7qW8/edit?usp=sharing

The only point I suggest we action before going live is the text in the filter bar. Other elements we may want to consider in future releases.

**Comment by jasonwebber-bl** [comment]
Text for filter bar: 
Current: Filter within ALL categories (111 collections available)
New: Filter ALL 111 collections (search is on collection title and description)

Note: where 'all 111 collections' appears would change to the category text if chosen by user. e.g. Filter History category (12 collections available) (search is on collection title and description)

**Comment by jasonwebber-bl** [comment]
To describe the issue:

- Users need to be able to easily see that this page is about categories and collections (and how many) - _Note - this is currently met with the present iteration_
- Users also need to know that they are searching on 'title' and 'description' only (not all the targets with a collection).

**Comment by jasonwebber-bl** [comment]
1. Slight change to new text:
From: (searching on 'title' and 'description' only)
To: (Searches on 'title' and 'description' only)

2. Can this text be there before a search is conducted? i.e. when there are no results.
This is important information before the first search.

**Comment by jasonwebber-bl** [comment]
Apologies, late tweak:

1. Text: (Searches on collection 'title' and 'description' only)
2. Nudge this text down a few pixels

I've asked for translations, we should get them back within a day or so.

**Comment by jasonwebber-bl** [comment]
English to welsh:

1. Searches on 'title' and 'description' only
2. Arts and Culture
3. History
4. Politics and Government
5. Places
6. Science Technology and Medicine
7. Society and Community
8. Sport and Recreation
9. Filter within all categories (xxx collections available)
10. No results
11. Results found
12. Show more
13. Show less

1. Chwiliadau yn ôl 'teitl' a 'disgrifiad' yn unig
2. Celfyddydau a Diwylliant
3. Hanes
4. Gwleidyddiaeth a Llywodraeth
5. Lleoedd
6. Gwyddoniaeth Technoleg a Meddygaeth
7. Cymdeithas a Chymuned
8. Chwaraeon a Hamdden
9. Hidlo o fewn pob categori (xxx o gasgliadau ar gael)
10. Dim canlyniadau
11. Canlyniadau a gafwyd
12. Dangos mwy
13. Dangos llai

**Comment by min2ha** [comment]
> English to welsh:
> 
> 1. Searches on 'title' and 'description' only
> 2. Arts and Culture
> 3. History
> 4. Politics and Government
> 5. Places
> 6. Science Technology and Medicine
> 7. Society and Community
> 8. Sport and Recreation
> 9. Filter within all categories (xxx collections available)
> 10. No results
> 11. Results found
> 12. Show more
> 13. Show less
> 14. Chwiliadau yn ôl 'teitl' a 'disgrifiad' yn unig
> 15. Celfyddydau a Diwylliant
> 16. Hanes
> 17. Gwleidyddiaeth a Llywodraeth
> 18. Lleoedd
> 19. Gwyddoniaeth Technoleg a Meddygaeth
> 20. Cymdeithas a Chymuned
> 21. Chwaraeon a Hamdden
> 22. Hidlo o fewn pob categori (xxx o gasgliadau ar gael)
> 23. Dim canlyniadau
> 24. Canlyniadau a gafwyd
> 25. Dangos mwy
> 26. Dangos llai

Sorry, but would it be possible rearrange translation representation? it would help to add precision on what is what just in case.

BTW, do we have a translation for 'All Collections' ?

**Comment by jasonwebber-bl** [comment]
I've added the welsh translations to the bottom of the spreadsheet:
https://docs.google.com/spreadsheets/d/1GHY97LeYeOvSBrrVdL-wKHy2W6ZV7h2DqI8aWev0vpU/edit?usp=sharing

Just asking about 'all collections'

**Comment by jasonwebber-bl** [comment]
**Conducted following tests:**
Try a search term - are results received, and do openly accessible results show as default (if not in the library)? **Yes**
Can you apply filters? (test 2-3, are the results as expected) **Yes**
Do restricted to reading room sites show as restricted? (test 2-3) **Yes**
Can you navigate from a result to an archived website  (test 2-3) **Yes**
Can you browse Topics and Themes? (test 2-3) **Yes**
Choose a thematic collection and check that it is possible to browse through the hierarchy (check all tiers) **Yes**
Can you navigate from the list of results to an archived web page? **Yes**
Can you access the 'Save a UK website' form **Yes**
Translations - if translations have been included - ask native reader to check **Requires checking with Scots Gaelic and welsh speakers**

Note: Scottish Gaelic Translations still required for T&T page. To be added in next Bugfix release.

Make live.

**Comment by jasonwebber-bl** [comment]
Let's go live.
