### ISSUE TITLE
Add Scottish Gaelic (and other languages) translations 

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#258]
Phase 0 - JW to identify Editorial methods for managing Translations in 4 languages.
Phase 1 - Agree ‘core text’ for translations, where this will be held and maintained. **Responsible: MV; Accountable: JW; Consulted: AJ** 
Text supplied to NLS for translation. **Responsible: NLS; Accountable: JW** 

1. Jason to collate text requiring additional translation
2. Ask NLS to translate extra text and return
3. Mindy to implement

**Comment by jasonwebber-bl** [comment]
Link to master text : https://docs.google.com/spreadsheets/d/1GHY97LeYeOvSBrrVdL-wKHy2W6ZV7h2DqI8aWev0vpU/edit#gid=0

**Comment by jasonwebber-bl** [comment]
Colour code system for updated or new text:

Recently added or amended (by translator)- Red
Ready to test - green
Ready for production - blue
Live - black

**Comment by jasonwebber-bl** [comment]
I've sent copies of the text to both NLW and NLS for some text updates. When this comes back we can add the sheet for scottish gaelic.

**Comment by anjackson** [comment]
Are the translations back?

**Comment by jasonwebber-bl** [comment]
The vast majority are. I have a couple more amendments to send through but the turnaround is usually very quick.

**Comment by jasonwebber-bl** [comment]
Welsh accessibility statement: https://docs.google.com/document/d/1vTNmGA-rzACotos77Z2iCVclHH7ZfAp7ynkkqYC9BsM/edit?usp=sharing

**Comment by jasonwebber-bl** [comment]
Please add the english language version of the accessibility statement to the scottish gaelic version for now.

**Comment by jasonwebber-bl** [comment]
Looks good. Ready to go live.
