### ISSUE TITLE
Create Alias for 'nominate'

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#265]
Create an alias to the 'save a website page':

Can 'https://www.webarchive.org.uk/nominate' go to 'https://www.webarchive.org.uk/en/ukwa/info/nominate'

We use this link a lot and would particularly like to use it on a leaflet that we are printing shortly.

[Helena] i've added you to the ticket so that you can see progress.

**Comment by GilHoggarth** [comment]
Are you wanting /cy/nominate to redirect to /cy/ukwa/info/nominate?
(I thought we now offered other languages too but don't see them from the website top-right options.)

**Comment by GilHoggarth** [comment]
Well you got cy too, which I accept isn't the best process (do without instruction). If you'd like it removed, let me know; other done, you can close the ticket.

**Comment by jasonwebber-bl** [comment]
Thanks for pointing this out. Yes as we may want to offer that redirect option to NLW or on a welsh language bit of literature at some juncture.

**Comment by jasonwebber-bl** [comment]
Works fab, thank you!
