### ISSUE TITLE
Url redirect to act userguide

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#266]
Please can you set up a redirect from:

http://www.webarchive.org.uk/act/userguide

to https://github.com/ukwa/w3act/wiki/W3ACT-User-Guide

I don't think that there is a welsh version to go to on this one. We are hoping to add this to a print leaflet too.

**Comment by HelenaByrne** [comment]
This link doesn't actually exist yet http://www.webarchive.org.uk/act/userguide

**Comment by GilHoggarth** [comment]
Whoa, after just 1 hour I'm already getting complaints about this task not being completed?!?
Anyway, "oh yes it is" as they say at Christmas. Apparently.
Left open for you to check and close if this satisfies your demands... ;)

**Comment by HelenaByrne** [comment]
That's great, thank you Gil :)

**Comment by anjackson** [comment]
This appears do be done! Re-open if not.
