### ISSUE TITLE
Results = 0 but results include a result

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#284]
I've put in a search www.oldkentmaps.co.uk and the results page says '0 results' but the top result is the correct website.
<img width="1152" alt="Screenshot 2020-09-10 at 10 38 57" src="https://user-images.githubusercontent.com/33252622/92712893-34631d00-f352-11ea-9353-476d99a7dc84.png">

**Comment by min2ha** [comment]
Other search cases:
same for 'oldkentmaps.co.uk'
and no results at all for 'oldkentmaps'

**Comment by jasonwebber-bl** [comment]
Looking on the live site, this seems to have resolved (in this example at least). Note: the search on dev doesn't return this site at all.

 https://www.webarchive.org.uk/en/ukwa/search?view_filter=vool&content_type=Web+Page&from_date=&to_date=&modal_filter_domains_vals=&modal_filter_suffix_vals=&modal_filter_documenttypes_vals=&modal_filter_collections_vals=&filter_source=1&filter_array_x=&filter_array_x_item=&search_location=full_text&text=https%3A%2F%2Fwww.oldkentmaps.co.uk&view_sort=relevant&view_count=50

**Comment by min2ha** [comment]
Related to https://github.com/ukwa/ukwa-ui/issues/253
