### ISSUE TITLE
Tips wording incorrect

### ISSUE THREAD

**Issue by crarugal** [ukwa/ukwa-ui#285]
![image](https://user-images.githubusercontent.com/18530934/94690681-51bf5180-0328-11eb-88de-52c37156f4ed.png)

I think  4 and 7 should be revised, as they're misleading. 

- We do have social media and it would be subjective to say what's a little amount, Facebook is also still added as targets (though not many). 

- The wording for no.7 is incorrect  e.g. NPLD.

**Comment by jasonwebber-bl** [comment]
Thanks. A few other bits to revise here too.

**Comment by jasonwebber-bl** [comment]
Ticket owner: JW
ACTION: JW to revise text

**Comment by jasonwebber-bl** [comment]
New text: 

3. Note on dates - they refer to the day archived NOT the day published.
4. The archive contains **some** social media (mostly Twitter) but is not comprehensive.
7. The majority of the UK Web Archive has been collected under the Non-Print Legal Deposit regulations 2013. Material collected this way can legally only be viewed in UK Legal Deposit reading rooms (on library terminals).

**Comment by jasonwebber-bl** [comment]
Can I change one more (sorry). Note: the others are fine.

6. 18,000+websites, collected from 2005 to the present, are publicly available online as we have the website owner's consent to make them available in this way.

**Comment by jasonwebber-bl** [comment]
Just realised that I gave the wrong number on one of the entries. For clarity, this is the full list below. 3,4,6 and 7 have changed from the original (live) version.

1  Use Boolean search terms - AND, NOT, OR etc. e.g. apple NOT fruit.
2  Use quote marks when looking for a specific phrase e.g. “London Olympics”.
3  Note on dates - they refer to the day archived NOT the day published.
4  The archive contains some social media (mostly Twitter) but is NOT comprehensive.
5  This is a collection of UK websites. The Archive contains many more .uk websites than other top level domains such as .com
6  18,000+websites, collected from 2005 to the present, are publicly available online as we have the website owner's consent to make them available in this way.
7  The majority of the UK Web Archive has been collected under the Non-Print Legal Deposit regulations 2013. Material collected this way can legally only be viewed in UK Legal Deposit reading rooms (on library terminals).
