### ISSUE TITLE
Add image to Duke of Edinburgh Collection on webarchive.org.uk

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/ukwa-ui#312]
Please can the following image be added to the Duke of Edinburgh Collection? 
Collection page in ACT:  https://www.webarchive.org.uk/act/collections/3866

Link to image: 
https://commons.wikimedia.org/wiki/File:Duke_of_Edinburgh_33_Allan_Warren.jpg
Image also attached to ticket
![Duke_of_Edinburgh_33_Allan_Warren](https://user-images.githubusercontent.com/11210500/116694743-8f1bb880-a9b7-11eb-87f1-bd0dd87a5a9c.jpg)

**Comment by min2ha** [comment]
Sorry, I guess its the Collection page on webarchive:
https://www.webarchive.org.uk/en/ukwa/collection/3866

**Comment by nicolabingham** [comment]
Hi @min2ha It should be added to this page "Topics and Themes" https://www.webarchive.org.uk/en/ukwa/collection/
for the Duke of Edinburgh collection. I've added an incorrect link at the head of this ticket which I'll remove.

**Comment by min2ha** [comment]
Thanks @nicolabingham, new image is ready for testing on Dev, just need some path update of collections resource instance from our tech team.

**Comment by nicolabingham** [comment]
The image is ok, thanks
