### ISSUE TITLE
Welsh translation correction (save a website page)

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#325]
The 'save a uk website' page needs a small update as one of the welsh translations hasn't come through. It revolves around the 'Name' field (still in english) and some code on the page.
![image](https://user-images.githubusercontent.com/33252622/129023067-8858065e-3f09-458a-97a0-ef7b15ad4701.png)

Actions: 

1. Change 'Name' to 'Enw'
2. Remove code

Note: In the master translation spreadsheet there appeared to be an * before the welsh word. I wonder if this threw it off when copied into the code?

**Comment by min2ha** [comment]
The problem was in translation source Excel file. 
The generator needs  correct input code as it'll be embedded into source code.

**Comment by jasonwebber-bl** [comment]
Works as expected. Ready for live.
