### ISSUE TITLE
Correction in Scottish Gaelic version - Italic font in the nomination form 

### ISSUE THREAD

**Issue by min2ha** [ukwa/ukwa-ui#327]
Italic font in Scottish Gaelic version

**Comment by min2ha** [comment]
The problem was in translation source Excel file.
The generator needs correct input code as it'll be embedded into source code.

**Comment by jasonwebber-bl** [comment]
Which word is this on? 

Is it this bit: 
![image](https://user-images.githubusercontent.com/33252622/130066101-88ff785a-16a1-4895-a149-37ab60122789.png)

If so, we can live with it for now while I find out which word has the italic.

**Comment by min2ha** [comment]
![33F7A6EB-C531-4206-B16C-D0C9FAEE86FB](https://user-images.githubusercontent.com/15713396/130068251-07fe7fbc-0feb-4aea-87ed-0533f73ca4e0.jpeg)

**Comment by jasonwebber-bl** [comment]
I agree, let's make it all non-italicized for now. Ready for live.
