### ISSUE TITLE
Collection image - Scottish Parliamentary Elections 2021

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#329]
Add this image to the 'Scottish Parliamentary elections 2021' collection (not live yet but will be shortly)
![Scottish Election 2021 graphic - white background (1)](https://user-images.githubusercontent.com/33252622/131506115-1650c0ae-6172-4e24-9496-9e3c4eceea7a.PNG)

**Comment by min2ha** [comment]
The ID of collection is 2132? right?

**Comment by jasonwebber-bl** [comment]
No, thats a different ticket. This collection seems to be one that isn't searchable on the T&T page although I believe it to be live. I'm afraid I don't know the number.

**Comment by nicolabingham** [comment]
The Collection id is 3466. @jasonwebber-bl it can be found by looking it up on ACT

**Comment by jasonwebber-bl** [comment]
Looks good.
