### ISSUE TITLE
Upgrade Google analytics to GA4

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#349]
https://support.google.com/analytics/answer/11583528

**Comment by anjackson** [comment]
This search shows where all the older Analytics integrations are: https://github.com/search?q=org%3Aukwa+google-analytics&type=code

And this covers PyWB https://github.com/ukwa/ukwa-pywb/issues/86 (which uses a slightly newer version of the analytics code)

**Comment by jasonwebber-bl** [comment]
I've checked with the BL comms and web teams on how they are processing this transition. They plan to add GA4 in the autumn and run both systems together for 6 months (until the end of Mar 23) while they are setting up the new 'events' in GA4. I think we should do the same approach. This would ensure continuity of current stats until the end of the 2022 reporting period and give us time to set up a new system.

**Comment by anjackson** [comment]
Thanks @jasonwebber-bl that makes sense. So we should just add the new tracking code, so that both are active, rather than replacing one with the other.

**Comment by anjackson** [comment]
@min2ha it should just be a case of pasting and adding in the HTML fragment in https://github.com/ukwa/ukwa-ui/issues/349#issuecomment-1111030511 into the UKWA-UI codebase in the right place.

https://github.com/ukwa/ukwa-ui/blob/d464f71e2ac0b463863ef9d78d3d2523b6990394/src/main/webapp/WEB-INF/jsp/footer.jsp#L249

**Comment by anjackson** [comment]
As this is a very small and simple change, I've asked @min2ha to include it in the 1.4.2 release.

**Comment by anjackson** [comment]
Logged into Google Analytics and I can verify that the visits are coming through for UKWA-UI.
