### ISSUE TITLE
Add a new Collection image to User Interface - Ukraine Collection id 4214

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/ukwa-ui#357]
Could this image be added to the Ukraine Collection please? 

https://unsplash.com/photos/FvqWnYo534s 

https://www.webarchive.org.uk/act/collections/4214

**Comment by jasonwebber-bl** [comment]
Can't test as collection not visible on the topics and theme page on dev (or live)

**Comment by anjackson** [comment]
LGTM https://www.webarchive.org.uk/en/ukwa/collection/4214
