### ISSUE TITLE
Searching for a URL in the UKWA Search does not return a result in Wayback. 

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/ukwa-ui#358]
Searching for a permission-cleared URL in Search on the UKWA website does not return a result in Wayback. 

Example 1: Live URL is https://www.gov.uk/government/publications/advice-from-the-independent-adviser-on-ministers-interests-december-2021
The URL in the Web Archive for the calendar page is https://www.webarchive.org.uk/wayback/en/archive/*/https://www.gov.uk/government/publications/advice-from-the-independent-adviser-on-ministers-interests-december-2021

Example 2: https://www.gov.uk/government/publications/build-back-better-our-plan-for-health-and-social-care

https://www.webarchive.org.uk/wayback/archive/*/https://www.gov.uk/government/publications/build-back-better-our-plan-for-health-and-social-care

(sorry I don't know if this the right repository to assign the issue to)

**Comment by anjackson** [comment]
Hm, @nicolabingham those two URLs are different - is they both examples that don't work right? Certainly searching for the first URL does not show a link to https://www.webarchive.org.uk/wayback/archive/*/https://www.gov.uk/government/publications/build-back-better-our-plan-for-health-and-social-care

**Comment by nicolabingham** [comment]
Sorry @anjackson that was a typo, I've updated the ticket

**Comment by anjackson** [comment]
I think this was resolved by the new URL search behaviour.
