### ISSUE TITLE
Update Cambridge logo

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#36]
We need to update the Cambridge logo.

**Comment by ldbiz** [comment]
![cambridge university library 600 logo_black landscape transparent](https://user-images.githubusercontent.com/16339290/33324201-d6bbcbfc-d446-11e7-9f00-d3a30c49d1b3.png)
![cambridge university library 600 logo_black portrait transparent](https://user-images.githubusercontent.com/16339290/33324202-d6d708b8-d446-11e7-9007-a43e2d938ac7.png)
![cambridge university library 600 logo_white landscape transparent](https://user-images.githubusercontent.com/16339290/33324203-d6f190d4-d446-11e7-9ebb-9cbbba23cc0f.png)
![cambridge university library 600 logo_white portrait transparent](https://user-images.githubusercontent.com/16339290/33324204-d7091650-d446-11e7-9bb0-fdffe7ea4c88.png)

**Comment by ldbiz** [comment]
![cambridge university library 600 logo_black landscape transparent](https://user-images.githubusercontent.com/16339290/33324250-f75a46cc-d446-11e7-84bb-0a4837aad3ae.png)

**Comment by ldbiz** [comment]
![cambridge university library 600 logo_black portrait transparent](https://user-images.githubusercontent.com/16339290/33324251-fc599308-d446-11e7-992d-50a58c7bee08.png)

**Comment by ldbiz** [comment]
![cambridge university library 600 logo_white landscape transparent](https://user-images.githubusercontent.com/16339290/33324254-02bc2bac-d447-11e7-86e2-76dda2d1809a.png)

**Comment by ldbiz** [comment]
![cambridge university library 600 logo_white landscape transparent](https://user-images.githubusercontent.com/16339290/33324263-0c5bc082-d447-11e7-9d91-1d094d4ae200.png)

**Comment by ldbiz** [comment]
![cambridge university library 600 logo_white portrait transparent](https://user-images.githubusercontent.com/16339290/33324273-155b8a46-d447-11e7-8ebc-f161d495e1fa.png)
