### ISSUE TITLE
Add image to Queen's Platinum Jubilee Collection

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/ukwa-ui#362]
Hi @min2ha please can you add a collection image to the Queen's Platinum Jubilee Collection? https://www.webarchive.org.uk/act/collections/4088
This is the image:
![queens_platinum_jubilee_english_0](https://user-images.githubusercontent.com/11210500/179721996-a6102d21-e76d-42d4-b00e-24ff903646df.png)
Alt text = "Queen's Platinum Jubilee Official Logo"

**Comment by jasonwebber-bl** [comment]
The image is square but will need to be adapted into the landscape format on the website. I recommend centering with white space on either side. @min2ha Let me know if this is ok?
