### ISSUE TITLE
Links to reading rooms on 'Resource only available in a reading room' page all broken

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#38]
Links to all the reading rooms are broken

**Comment by GilHoggarth** [comment]
@jasonwebber-bl Could you add more information please. I.e., this is where this is seen, this is what is done to see this, the message that is communicated to the viewer....

**Comment by anjackson** [comment]
Sorry, @jasonwebber-bl I logged this as #39!

**Comment by anjackson** [comment]
Closing as a duplicate of #39.
