### ISSUE TITLE
Search box not accepting characters on mobile

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#4]
Home page search box wouldn't accept characters when typed.

Also, the tooltip indicating the empty field is misplaced, it points above the field, not to it.

Moto g4, Android  7, Chrome

**Comment by ldbiz** [comment]
I've just tried it again, and it's working. I'll assume user error and close and reopen if I reproduce it.

**Comment by ldbiz** [comment]
Reopened, don't know if it's phone/browser specific, but I haven't noticed it on other sites.

Definitely happening first time into the search box when I log in. Starts working after I've clicked a couple of things.

**Comment by bzaar** [comment]
We've tested this on https://dev.webarchive.org.uk in a number of browsers and phones and could not reproduce.

What phone/browser did this appear in?

**Comment by ldbiz** [comment]
Thanks for feedback. See first comment for platform. 

It's worked the last couple of times I've tried. I'll try working out how exactly to reproduce it and maybe record it happening. 

If it's an obscure environment issue it'll be very low priority.
