### ISSUE TITLE
Error 500 on link search

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#41]
enter http://henryjacksonsociety.org/ into search box and get 'error 500 server error'

enter henryjacksonsociety.org/ and it works fine (the website expected is the top result

**Comment by min2ha** [comment]
![error500_41](https://user-images.githubusercontent.com/15713396/33599900-8a44e2dc-d99f-11e7-9c04-f9cbc464dd56.png)

**Comment by anjackson** [comment]
May be the same issue, but searching for a DOI also breaks stuff. e.g. [doi:10.1136/vr.103779](https://beta.webarchive.org.uk/en/ukwa/search?view_filter=va&from_date=&to_date=&search_location=full_text&text=doi%3A10.1136%2Fvr.103779&view_sort=nto&view_count=50) should look something like [this](https://beta.webarchive.org.uk/en/ukwa/search?view_filter=va&from_date=&to_date=&search_location=full_text&text=10.1136%2Fvr.103779&view_sort=nto&view_count=50).

**Comment by min2ha** [comment]
Yes, it is fixed alredy. 
Tested on **dev.webarchive.org.uk**:

![error500_41_doi](https://user-images.githubusercontent.com/15713396/33670144-48c6c7e6-da9c-11e7-9d0b-70a6b76b82db.png)

**Comment by jasonwebber-bl** [comment]
Works great, please include in the next update to Beta.

**Comment by anjackson** [comment]
This doesn't seem to work on Beta?!

**Comment by anjackson** [comment]
Hah, it didn't work on Beta because ALL SEARCHES FAILED because I broke the deployment!

Works fine now.
