### ISSUE TITLE
Replace logo for NLS

### ISSUE THREAD

**Issue by jasonwebber-bl** [ukwa/ukwa-ui#42]
The NLS logo in the footer needs replacing (i've emailed the new jpg to Mindy and Lee)

**Comment by jasonwebber-bl** [comment]
It seems disproportionally small compared to the others, can it be made bigger?

**Comment by min2ha** [comment]
I noticed that, but the rest presented logos, which have good proportions compared to each other and no changes needed. If it is acceptable we could just simply cut off some white space or wait more interoperable NLS logo.

**Comment by jasonwebber-bl** [comment]
Let's try it

**Comment by min2ha** [comment]
Done

**Comment by jasonwebber-bl** [comment]
Looks great, happy for this to be included in the next update to Beta.

**Comment by anjackson** [comment]
This seems to have worked?
