### ISSUE TITLE
Site should display some kind of 'busy indicator' when running searches

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#69]
User's need instant feedback to know their query is being processed. So, we need some kind of busy-indicator (as we had in Shine).

**Comment by ldbiz** [comment]
That seems to be working - minor grammar note though: "Please wait" should have 3 dots (periods/full-stops) appended, not 2. I note that 3 _are_ in the code, so wonder if something has been clipped off?

**Comment by ldbiz** [comment]
In what way is this issue different to #60 ?

**Comment by min2ha** [comment]
Same, could be closed. It was because of 2 separate branches.

**Comment by ldbiz** [comment]
cheers, done

**Comment by ldbiz** [comment]
Looks good!
