### ISSUE TITLE
Topic & Theme page title and 'featured' status

### ISSUE THREAD

**Issue by anjackson** [ukwa/ukwa-ui#76]
All Topics and Themes are marked as 'featured' - I think we only want that on the home page if at all.

Also, the title is still Special Collections rather than Topics and Themes.

**Comment by ldbiz** [comment]
This looks all good - a minor grammatical question for maybe @jasonwebber-bl or @nicolabingham:

![image](https://user-images.githubusercontent.com/16339290/43081609-07001036-8e8a-11e8-9e9c-4fee8f4a6e78.png)

This wording looks off to me - it should be one or the other ("topic" or "theme"), or the conjunction should be "or" instead.

e.g. 

Search "Blogs and Social Media" topic OR

Search "Blogs and Social Media" topic or theme

If you are ok with the wording as is, this can be passed I think.

**Comment by nicolabingham** [comment]
coudl you provide a bit more contextual information about the text please? Where does it come from, is it part of a larger document? I'll try to help if I can in Jason's absence!

**Comment by ldbiz** [comment]
http://192.168.45.25:6060/en/ukwa/collection/911

The search field prompt.

**Comment by ldbiz** [comment]
After discussion with NB: 

Please change the wording from 

Search "Blogs and Social Media" topic and theme

to:

Search within "Blogs and Social Media"

If that's tricky for some reason, we can revisit.

**Comment by nicolabingham** [comment]
thanks

**Comment by min2ha** [comment]
Okay, sorted. It is: 
**Search _something_ within Blogs and Social Media**
for now

**Comment by ldbiz** [comment]
Unfortunately I don't think that makes sense. It needs to be as described above. Keep everything as is, just drop the "topic and theme" and add the word "within". Keep the quotes as they are in the existing text, let me know if you need further clarification.

Examples I've failed: 

![image](https://user-images.githubusercontent.com/16339290/43084555-d44371ea-8e90-11e8-8df5-8cd799d6aeae.png)

![image](https://user-images.githubusercontent.com/16339290/43084580-e1f192b8-8e90-11e8-9578-0d583b3c0745.png)

**Comment by ldbiz** [comment]
Still there, I think we might have crossed wires...

![image](https://user-images.githubusercontent.com/16339290/43085689-837c3f50-8e93-11e8-8e2e-cfab38cb514f.png)

Should read *exactly* as follows:

Search within "Blogs and Social Media"

**Comment by min2ha** [comment]
It was some delay, it works for me

![image](https://user-images.githubusercontent.com/15713396/43086931-7b707558-8e96-11e8-8ed1-1a4f90c52f8e.png)

**Comment by ldbiz** [comment]
Cheers - needs quotes though.

Search within "Blogs and Social Media"

**Comment by ldbiz** [comment]
Also I've just tested it on another collection:

http://192.168.45.25:6060/en/ukwa/collection/918

![image](https://user-images.githubusercontent.com/16339290/43089146-e15b2660-8e9b-11e8-9f3f-1fca7110734e.png)

**Comment by min2ha** [comment]
Sorry because of use of general terms like Blogs and Social media I've misunderstood the point. 
Hope it is fine now.

**Comment by nicolabingham** [comment]
thanks @min2ha and @ldbiz this is working fine now.
