### ISSUE TITLE
Search Page - Re-design - Reset Filter

### ISSUE THREAD

**Issue by min2ha** [ukwa/ukwa-ui#86]
Re-design - Reset Filter:
- Text change 
- Add new CSS Styles
- Button shape, colours, fonts
- Rearrange elements

**Comment by ldbiz** [comment]
I assume this is referring to https://trello.com/c/BVdywtEj/23-redesign-access-panel-to-better-communicate-why-only-some-content-is-available-address-subset-and-consistency-issue-only-need-on

and will test against that.

**Comment by ldbiz** [comment]
Design text: "Viewable Online" .
Delivered text: "Online".

![image](https://user-images.githubusercontent.com/16339290/43724534-1edd708c-9992-11e8-94f6-e38ef3e67dab.png)

**Comment by ldbiz** [comment]
![image](https://user-images.githubusercontent.com/16339290/43968524-52637f52-9cbf-11e8-97a6-3af95bb0d1c9.png)

I'm concerned that basic mobile view looks wrong via Chrome Dev Tools so failing on that basis. We can review though and raise as a separate issue if it looks like being a blocker.

Also I think the right alignment should of the fields should mirror the left, so they are centred within the separator lines below.

![image](https://user-images.githubusercontent.com/16339290/43968630-a9d3060e-9cbf-11e8-9790-f2cfe49084a8.png)

Apart from that though, I think it's looking good.

**Comment by ldbiz** [comment]
2. Also I think the right alignment of the fields should mirror the left, so they are centred within the separator lines below.

![image](https://user-images.githubusercontent.com/16339290/43968868-4a9a511e-9cc0-11e8-864e-218e4ceb0806.png)

**Comment by ldbiz** [comment]
3. If you click "Show More" under Topics and Themes, the list items overlap.

![image](https://user-images.githubusercontent.com/16339290/43969107-0778f074-9cc1-11e8-8a04-b6e42fd17557.png)

![image](https://user-images.githubusercontent.com/16339290/43969063-dba20a3a-9cc0-11e8-8588-21cef7ed351b.png)

**Comment by ldbiz** [comment]
If any of the above look like being time-drags and it is okayed we can look at passing this and creating them as separate issues for a future alpha iteration. Failed in the meantime.

**Comment by min2ha** [comment]
Could anybody suggest what to do with **long names** in Filtering ? Should it fit to single or two lines? What policy to use truncating the too long name string?

**Comment by nicolabingham** [comment]
As discussed today, @ldbiz to reach out to James Rennie and/or Mark Whiting for advice on this. If we don't hear from them suggest that we follow @ldbiz 's recommendation with the text to go over two lines.

**Comment by ldbiz** [comment]
Advice requested. We also need to bear in mind that if we wrap to a maximum n lines, n might need to be increased as the width of the window shrinks.

**Comment by ldbiz** [comment]
btw I note it seems to fix itself when resizing the window small then large again...

**Comment by ldbiz** [comment]
Discussion with other UX people here, consensus is:

1. Maximum 3 lines, crop after that. Results in bracket still to be at the end.
2. Consider how we can enforce or encourage shorter topic names, or at least topic facet names. I'll create another issue for that for a possible future enhancement.

**Comment by ldbiz** [comment]
I've raised the following 2 issues to be fixed outside of this one:

Mobile rendering: #119
Topic title length reductions: #118

Please commit any work for them against those issues, not this one.

The other failures in testing can be reworked against this issue, unless they look like being significant changes in which case we can raise new ones:

Margins for the facet summary display at the top (the red lines above).
Facet wrapping limit of 3 lines.

**Comment by ldbiz** [comment]
Margins: passed.

Facet wrapping: failed.

![image](https://user-images.githubusercontent.com/16339290/44149258-4db67202-a093-11e8-9d28-5bd8bc634c3b.png)

**Comment by ldbiz** [comment]
Facet wrapping good to go, we can create follow on issues for the more minor stuff. e.g. #125
