### ISSUE TITLE
Text - Change Wording for Date Archived

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#92]
See Also #70 

Wording should be changed from "Date Archived" to "Date Collected"

**Comment by ldbiz** [comment]
https://trello.com/c/D72ZGrW9/3-change-wording-on-date-archived

**Comment by ldbiz** [comment]
Translations needed.

**Comment by nicolabingham** [comment]
@jasonwebber-bl this text is to be added to the list for translation.
