### ISSUE TITLE
Search should default to phrase searching

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#96]
https://trello.com/c/dg3KzrPU/14-results-should-be-weighted-or-default-to-the-whole-string-searched-on-rather-than-treated-as-or-be-clear-to-users-that-this-is-t

Results should be weighted (or default) to the whole string searched on (rather than treated as OR). 

Be clear to users that this is the case. 

Offer clear alternative e.g. did you mean xxxx OR xxxx OR

We need this to be consistent and acceptable in the context of LDLs and BL main products.

**Comment by ldbiz** [comment]
Think we need a bit more clarity on this. There are standard ways of searching online; user's expectations will be aligned with (say) Google. 

We may not be able to match the accuracy, but IMO we should be interpreting the queries in the same way.

**Comment by ldbiz** [comment]
Example queries and expected interpretations required.

**Comment by nicolabingham** [comment]
My vote would be to default to searching on the whole text string with the clearer alternative, "did you mena xxx OR xxx". This is certainly how the BL main website performs and I think user expectation generally expects this.
