### ISSUE TITLE
Facet text improvements

### ISSUE THREAD

**Issue by ldbiz** [ukwa/ukwa-ui#99]
Consider showing some examples of top facet text (this explains the labels domain and suffix) and add ‘more’. See eBay for example of handling large facet numbers

Translation may be needed (eg if there is a "more" button)

Eg number of Domains shown - eg prefer domains for resources in ACT, prefer domains with most results

https://trello.com/c/6ArtF5EG/25-consider-showing-some-examples-of-top-facet-text-this-explains-the-labels-domain-and-suffix-and-add-more-see-ebay-for-example-of

**Comment by ldbiz** [comment]
More detail of exact requirements needed please before this can be developed against.

**Comment by jasonwebber-bl** [comment]
I'm happy with the text.

Some of the question marks overlap the text.

Also the gaps between the facets seems too much at the moment?

**Comment by crarugal** [comment]
The text that is provided when hovering over the question mark may not be understood by average user:  "...facet help tooltip"; not sure if this needs improving or just needs changing of the text.

https://dev.webarchive.org.uk/en/ukwa/search?text=hello&search_location=full_text&reset_filters=false&content_type=Web+Page

![image](https://user-images.githubusercontent.com/18530934/45298717-49a5d680-b501-11e8-8b7a-c95b2ab948ac.png)

![image](https://user-images.githubusercontent.com/18530934/45299000-16177c00-b502-11e8-8133-3a9deb5d77ef.png)

**Comment by min2ha** [comment]
same is on beta, tho.
https://beta.webarchive.org.uk

Suggestions are welcome.

**Comment by crarugal** [comment]
Mindy i think this could be closed,  but I'll create two new related issues; they may not be considered issues, in which case they could closed or merged with other issues.
1) consider changing the text provided when hovering over the question mark.
2) blue button for show more is not functional
